# El método de K-means

In [2]:
import numpy as np


In [3]:
data = np.random.random(90).reshape(30,3)
data

array([[0.65492745, 0.13650843, 0.051426  ],
       [0.11908397, 0.46219341, 0.00968542],
       [0.80183539, 0.45741649, 0.94270965],
       [0.76194325, 0.69578402, 0.75414923],
       [0.22382632, 0.38174269, 0.67945658],
       [0.50199415, 0.14020055, 0.7235445 ],
       [0.45924814, 0.71067272, 0.13279802],
       [0.48366336, 0.70231638, 0.88109271],
       [0.63178683, 0.67587616, 0.30123613],
       [0.77268948, 0.12718858, 0.11580019],
       [0.91041578, 0.31222512, 0.74868743],
       [0.01676802, 0.10229229, 0.05665928],
       [0.11689069, 0.98185623, 0.91198633],
       [0.57952142, 0.60507994, 0.51641535],
       [0.28114723, 0.23949248, 0.96386827],
       [0.61528821, 0.08331377, 0.05115474],
       [0.08379958, 0.41562783, 0.44797972],
       [0.41074955, 0.72943493, 0.80766013],
       [0.3845453 , 0.9025157 , 0.40434339],
       [0.50239644, 0.62508444, 0.88968293],
       [0.55067102, 0.64302395, 0.89775111],
       [0.31563603, 0.67632236, 0.29688345],
       [0.

In [4]:
c1 = np.random.choice(range(len(data)))
c2 = np.random.choice(range(len(data)))
clust_centers = np.vstack([data[c1], data[c2]])
clust_centers

array([[0.28114723, 0.23949248, 0.96386827],
       [0.3845453 , 0.9025157 , 0.40434339]])

In [5]:
from scipy.cluster.vq import vq

In [6]:
vq(data, clust_centers)

(array([1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1,
        1, 0, 0, 1, 1, 1, 0, 1]),
 array([0.88567732, 0.64815765, 0.56484929, 0.55455507, 0.32312663,
        0.34115651, 0.3407655 , 0.51192825, 0.35089167, 0.9138081 ,
        0.66900803, 0.94683783, 0.57934037, 0.37288583, 0.        ,
        0.92145337, 0.57394417, 0.43966807, 0.        , 0.45070593,
        0.48974708, 0.25972977, 0.4407544 , 0.5294887 , 0.53084686,
        0.48834218, 0.78055871, 0.69749029, 0.59898443, 0.24943168]))

In [7]:
from scipy.cluster.vq import kmeans

In [8]:
kmeans(data, clust_centers)

(array([[0.52239128, 0.58047954, 0.7941863 ],
        [0.47954008, 0.42519976, 0.2313419 ]]),
 0.3691435458225206)

In [14]:
kmeans(data, 2)

(array([[0.48684737, 0.38848315, 0.21803409],
        [0.5142827 , 0.59942284, 0.77125437]]),
 0.36789674551488916)